myPatisserie/Controllers/DataTransferController.cs
using myPatisserie.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace myPatisserie.Controllers
{
    public class DataTransferController : Controller
    {
        // GET: DataTransfer
        public ActionResult Index()
        {
            return View(0);
        }
        [HttpPost]
        public ActionResult Index(int sayi)
        {
            return View(sayi * sayi);
        }

        public ActionResult AjaxIndex()
        {
            return View(0);
        }

        [HttpPost]
        public int AjaxIndex(int sayi)
        {
            return sayi * sayi;
        }

        public int AjaxReq(int karesiAlinacakSayi,string name)
        {
            return karesiAlinacakSayi* karesiAlinacakSayi;
        }

        public ActionResult AjaxreqWithJsonResult()
        {
            LoginItem result = new LoginItem();
            result.UserName = "ibrahim";
            result.Password = "yzc";
            return Json(result);
        }
    }
}

myPatisserie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

myPatisserie/Views/Shared/_myLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My patisserie Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Patisserie", "Index", "Patisserie")</li>
                    <li>@Html.ActionLink("NotAjax", "Index", "DataTransfer")</li>
                    <li>@Html.ActionLink("Ajax", "AjaxIndex", "DataTransfer")</li>
                </ul>
                @{ if (Session["UserName"] != null)
                    {
                        <span class="merhaba"> Merhaba @Session["UserName"]</span>
                        <span class="merhaba">   @Html.ActionLink("Logout", "Logout", "Home")</span>
                    }
                    else
                    {
                        <span class="merhaba"> @Html.ActionLink("Login page", "Login", "Home")</span>
                    }
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>